import type { SkillConfig } from "@/types/skill";

export function renderReadmeMd(config: SkillConfig): string {
  const lines: string[] = [];
  lines.push(`# ${config.packageName}`, "");
  lines.push(config.description, "");

  lines.push("## What this skill is");
  lines.push(
    `A reusable AI Agent Skill package for ${labelForCategory(config.category)} workflows, generated by AxDD Skill Builder.`,
    "",
  );

  lines.push("## Who it is for");
  lines.push(
    "Designers, makers, and product builders using AI tools to plan and implement web or mobile products.",
    "",
  );

  lines.push("## Package structure");
  lines.push("```txt");
  lines.push(`${config.packageName}/`);
  if (config.packageOptions.includeSkillMd) lines.push("├── SKILL.md");
  if (config.packageOptions.includeReadme) lines.push("├── README.md");
  if (config.packageOptions.includeReferences) {
    lines.push("├── references/");
    lines.push("│   ├── ux-principles.md");
    lines.push("│   ├── ui-patterns.md");
    if (config.roleProfile.designSystemAwareness)
      lines.push("│   ├── design-system-rules.md");
    if (config.qualityRules.includes("include-accessibility"))
      lines.push("│   └── accessibility-checklist.md");
  }
  if (config.packageOptions.includeTemplates) {
    lines.push("├── templates/");
    lines.push("│   ├── ux-brief-template.md");
    lines.push("│   ├── screen-spec-template.md");
    lines.push("│   ├── design-review-template.md");
    if (config.outputFormat.includeCursorPrompt)
      lines.push("│   └── cursor-prompt-template.md");
  }
  if (config.packageOptions.includeExamples) {
    lines.push("└── examples/");
    lines.push("    └── ux-ui-example.md");
  }
  lines.push("```", "");

  lines.push("## How to install or use");
  lines.push(
    "1. Drop this folder into your AI agent's skill / instruction directory.",
    "2. Point the agent at `SKILL.md` as the entry instruction.",
    "3. Reference `templates/` and `references/` as needed during work.",
    "",
  );

  lines.push("## How to customize");
  lines.push(
    "- Edit `SKILL.md` to change role, workflow, output, or rules.",
    "- Add new templates under `templates/` and reference them from `SKILL.md`.",
    "- Add new references under `references/` for domain knowledge that the agent should consult.",
    "",
  );

  lines.push("## Example prompts");
  lines.push(
    "- *Design an order status screen for a food delivery app.*",
    "- *Review this signup screen and list UX issues by priority.*",
    "- *Turn this screen spec into a Cursor-ready implementation prompt.*",
    "",
  );

  return lines.join("\n");
}

function labelForCategory(category: SkillConfig["category"]): string {
  switch (category) {
    case "ux-ui":
      return "UX/UI design";
    case "product":
      return "product planning";
    case "frontend":
      return "frontend implementation";
    case "design-system":
      return "design system";
    case "research":
      return "research";
    case "content":
      return "content planning";
    case "data":
      return "data analysis";
    case "harness":
      return "harness setup";
  }
}
