import type { SkillBlock } from "@/types/skill";

export const UX_PRINCIPLES: SkillBlock = {
  id: "ref-ux-principles",
  category: "reference",
  title: "UX Principles",
  description: "Reusable UX principles for screen and flow design.",
  content: [
    "# UX Principles",
    "",
    "## 1. One Primary Action",
    "Every screen has exactly one primary action. Secondary actions are visually de-emphasized.",
    "",
    "## 2. Information Hierarchy",
    "Rank content by importance to the primary action. The most important content occupies the most visual weight.",
    "",
    "## 3. Make States Explicit",
    "Default, empty, loading, and error states are not optional — design them up front.",
    "",
    "## 4. Reduce Decisions",
    "Defaults should fit the common case. Configuration should be progressive.",
    "",
    "## 5. Respect the User's Time",
    "Latency and friction are first-class design concerns, not engineering footnotes.",
  ].join("\n"),
};

export const UI_PATTERNS: SkillBlock = {
  id: "ref-ui-patterns",
  category: "reference",
  title: "UI Patterns",
  description: "Common UI patterns and when to use them.",
  content: [
    "# UI Patterns",
    "",
    "## Navigation",
    "- **Top tabs** — Few peer sections (2–5), frequent switching.",
    "- **Side nav** — Many sections, hierarchical, desktop-first.",
    "- **Bottom tabs** — Mobile, 3–5 top-level destinations.",
    "",
    "## Forms",
    "- Group related fields. Label above input.",
    "- Inline validation on blur, not on every keystroke.",
    "- Surface a single primary submit; place destructive actions away from it.",
    "",
    "## Lists",
    "- For 0 items, design an empty state with a clear next action.",
    "- For long lists, paginate or virtualize; never block the main thread.",
    "",
    "## Modals",
    "- Use for focused, single-purpose interactions.",
    "- Avoid stacking modals; prefer inline expansion.",
  ].join("\n"),
};

export const DESIGN_SYSTEM_RULES: SkillBlock = {
  id: "ref-design-system-rules",
  category: "reference",
  title: "Design System Rules",
  description: "Token, primitive, and component rules.",
  content: [
    "# Design System Rules",
    "",
    "## Tokens",
    "- Color tokens are semantic (e.g., `surface`, `ink`, `accent`), not literal (`blue-500`).",
    "- Spacing is on an 8px scale with sub-base 4px for tight adjustments.",
    "- Radius is on a small scale: `sm`, `md`, `lg`, `pill`.",
    "",
    "## Primitives",
    "- Button, Input, Select, Checkbox, Radio, Card, Modal, Toast.",
    "- Each primitive owns its variants and states.",
    "",
    "## Components",
    "- Components compose primitives. Components do not redefine tokens.",
    "- A component's API is small, named, and documented.",
  ].join("\n"),
};

export const ACCESSIBILITY_CHECKLIST: SkillBlock = {
  id: "ref-accessibility",
  category: "reference",
  title: "Accessibility Checklist",
  description: "WCAG AA-oriented checklist.",
  content: [
    "# Accessibility Checklist",
    "",
    "- [ ] Color contrast meets WCAG AA for body text (≥ 4.5:1) and large text (≥ 3:1).",
    "- [ ] All interactive elements are reachable by keyboard.",
    "- [ ] Focus state is visible and clearly distinguishable.",
    "- [ ] Form inputs have associated labels.",
    "- [ ] Images convey meaning through `alt` or are marked decorative.",
    "- [ ] Headings form a coherent outline (no skipped levels).",
    "- [ ] Motion can be reduced via `prefers-reduced-motion`.",
    "- [ ] Touch targets are at least 44×44 px on mobile.",
  ].join("\n"),
};
