import type { SkillBlock, WorkflowModule } from "@/types/skill";

export const WORKFLOW_BLOCKS: Record<WorkflowModule, SkillBlock> = {
  "problem-definition": {
    id: "wf-problem-definition",
    category: "workflow",
    title: "Problem Definition",
    description: "Restate the user problem in concrete terms before producing screens.",
    content: [
      "### Problem Definition",
      "",
      "**When to enter this mode**",
      "- User describes a feature, screen, or product as a paragraph or shorter.",
      '- User says "design X" without providing existing screens.',
      "- A prior `ux-review` flagged a structural problem requiring a rethink.",
      "",
      "**Required inputs**",
      "- One sentence describing what the user wants.",
      "- The primary user role.",
      '- The success state — what does "done" look like, observably?',
      "",
      "If any input is missing, **ASK** before producing anything.",
      "",
      "**Steps**",
      "",
      "1. **Restate** the user's request in this exact form:",
      "   `[User role] wants to [action] so that [outcome].`",
      "   If you cannot fit it in one sentence, the problem is not one problem — split it.",
      "",
      "2. **Identify the primary user precisely.**",
      '   `"Customer"` is too vague. `"First-time customer who lands from a marketing email"` is precise.',
      "   Note what they already know and what they don't.",
      "",
      "3. **Map the trigger.** Where did the user come from? What just happened?",
      '   A user from `"Forgot password"` has a different mental state than one logging in fresh.',
      "",
      "4. **List unknowns.** Every assumption you'd have to make.",
      "   For each: (a) ask the user, (b) reasonable default, or (c) defer.",
      "",
      "5. **Define success** as observable behavior, not feelings.",
      '   `"User completes signup"` — observable. `"User feels confident"` — not.',
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "problem": "[Role] wants to [action] so that [outcome].",',
      '  "user": { "role": "...", "context": "...", "knownState": "..." },',
      '  "trigger": "...",',
      '  "successCriteria": ["observable behavior 1", "observable behavior 2"],',
      '  "unknowns": [',
      '    { "question": "...", "resolution": "ask" | "default" | "defer", "default": "..." }',
      "  ]",
      "}",
      "```",
      "",
      "**Common mistakes**",
      "- Restating the user's words verbatim instead of synthesizing.",
      '- Calling the user `"the customer"` without specifying *which* customer.',
      "- Skipping the trigger — leads to designing a screen out of context.",
      '- Defining success as `"fewer support tickets"` — true but not actionable here.',
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if you cannot fill the problem sentence in the required form.",
      "- STOP if `successCriteria` contains a feeling rather than a behavior.",
      "- STOP if `unknowns` is empty AND the user's request is shorter than 3 sentences — you missed assumptions.",
    ].join("\n"),
  },
  "user-flow": {
    id: "wf-user-flow",
    category: "workflow",
    title: "User Flow",
    description: "Map the happy-path and key alternates.",
    content: [
      "### User Flow",
      "1. List the happy-path steps from entry to success.",
      "2. Mark every decision point with explicit branches.",
      "3. Annotate failure or empty states.",
    ].join("\n"),
  },
  "information-architecture": {
    id: "wf-ia",
    category: "workflow",
    title: "Information Architecture",
    description: "Define screens, navigation, and content hierarchy.",
    content: [
      "### Information Architecture",
      "1. Enumerate the screens involved.",
      "2. Define the navigation model (tabs, stack, modal).",
      "3. Rank content priority within each screen.",
    ].join("\n"),
  },
  "screen-design": {
    id: "wf-screen-design",
    category: "workflow",
    title: "Screen Design",
    description: "Produce screen-level specs with hierarchy and primary action.",
    content: [
      "### Screen Design",
      "",
      "**When to enter this mode**",
      "- `problem-definition` and at least one of `user-flow` / `information-architecture` are complete.",
      "- User asks for a specific screen by name.",
      "",
      "**Required inputs**",
      "- Screen name and purpose (one sentence).",
      "- Entry point and exit point in the flow.",
      "- Primary user role for this screen.",
      "",
      "If any input is missing, **ASK** before proceeding.",
      "",
      "**Decision rules**",
      "- If the primary action is unclear, list candidate actions and let the user pick. Do not guess.",
      '- If two actions compete for "primary," one is wrong. Demote or split the screen.',
      "- If you cannot name the empty state's `next step`, the empty state is broken — fix it before continuing.",
      "- If you cannot describe an error state in one sentence, you don't understand the failure mode.",
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "screen": "ScreenName",',
      '  "purpose": "one sentence",',
      '  "primaryAction": { "label": "...", "destination": "..." },',
      '  "hierarchy": ["most important", "second", "third"],',
      '  "components": [',
      '    { "name": "ComponentName", "purpose": "...", "variants": ["..."], "states": ["..."] }',
      "  ],",
      '  "states": {',
      '    "default": "...",',
      '    "empty": { "trigger": "no data", "design": "...", "nextStep": "..." },',
      '    "loading": "skeleton shape",',
      '    "error": { "trigger": "...", "design": "...", "recovery": "..." }',
      "  },",
      '  "responsive": {',
      '    "mobile": "single column, sticky bottom CTA",',
      '    "tablet": "...",',
      '    "desktop": "..."',
      "  }",
      "}",
      "```",
      "",
      "**Common mistakes**",
      "- Listing UI elements before naming the primary action.",
      '- Treating `"empty"` as a missing screen instead of a designed state.',
      "- Componentizing too early — name the screen-level structure first.",
      '- Designing only the happy path. The error state is part of the design, not an afterthought.',
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if `primaryAction` is missing.",
      "- STOP if any of `{default, empty, loading, error}` is unspecified.",
      "- STOP if `hierarchy` has more than 5 items — the screen is overloaded.",
      "- STOP if any responsive variant is `\"same as desktop\"` — that's not a design decision.",
    ].join("\n"),
  },
  "component-breakdown": {
    id: "wf-component-breakdown",
    category: "workflow",
    title: "Component Breakdown",
    description: "Decompose screens into reusable components.",
    content: [
      "### Component Breakdown",
      "1. Identify reusable components across screens.",
      "2. Define props, variants, and states per component.",
      "3. Note responsive behavior and breakpoints.",
    ].join("\n"),
  },
  "design-system-draft": {
    id: "wf-design-system-draft",
    category: "workflow",
    title: "Design System Draft",
    description: "Draft the token and primitive layer.",
    content: [
      "### Design System Draft",
      "1. Propose color, typography, spacing, and radius tokens.",
      "2. Define primitive components (Button, Input, Card, etc.).",
      "3. Map screen elements to tokens and primitives.",
    ].join("\n"),
  },
  "figma-to-code": {
    id: "wf-figma-to-code",
    category: "workflow",
    title: "Figma to Code",
    description: "Translate visual specs into implementation plans.",
    content: [
      "### Figma to Code",
      "1. Produce a scene graph of the screen.",
      "2. Map each node to a component and its tokens.",
      "3. Output a Tailwind/React implementation outline.",
    ].join("\n"),
  },
  "ux-review": {
    id: "wf-ux-review",
    category: "workflow",
    title: "UX Review",
    description: "Review existing screens against rules and surface prioritized issues.",
    content: [
      "### UX Review",
      "",
      "**When to enter this mode**",
      "- User provides an existing screen (screenshot, Figma link, URL, code) and asks for review.",
      '- User says variations like `"review this"`, `"find issues"`, `"what would you improve"`.',
      "",
      "**Required inputs**",
      "- The screen artifact (image / code / URL).",
      "- The screen's intended primary action (ASK if not provided — the review depends on it).",
      "- The primary user role.",
      "",
      "**Audit checklist (run in order)**",
      "",
      "1. **Primary action audit**",
      "   - Can a first-time user identify the primary action in under 3 seconds?",
      "   - Is the primary action visually dominant (size, contrast, isolation)?",
      "   - If no — that is the top finding. Stop the rest of the audit until this is resolved.",
      "",
      "2. **Hierarchy audit**",
      "   - Rank content priority by reading order. Does the design match the rank?",
      "   - Find any element that is visually heavy but informationally minor (and vice versa).",
      "",
      "3. **States audit**",
      "   - Default present. Empty present? Loading present? Error present?",
      "   - For each missing state, flag as a finding.",
      "",
      "4. **Accessibility audit**",
      "   - Color contrast at AA (4.5:1 body, 3:1 large text).",
      "   - Keyboard reachability and visible focus.",
      "   - Touch targets ≥ 44 px (mobile) / 32 px (desktop).",
      "",
      "5. **Consistency audit**",
      "   - Same intent expressed two different ways? (e.g., two button styles for the same action.)",
      "   - Spacing snaps to the grid?",
      "",
      "6. **Microcopy audit**",
      '   - Button labels are verbs and concrete (`"Save changes"` not `"OK"`).',
      "   - Error messages explain what failed AND what to do next.",
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "summary": "one-line verdict",',
      '  "findings": [',
      "    {",
      '      "id": "F-01",',
      '      "category": "primary-action" | "hierarchy" | "states" | "accessibility" | "consistency" | "microcopy",',
      '      "severity": "blocker" | "major" | "minor",',
      '      "observation": "what is wrong (factual)",',
      '      "impact": "what the user experiences as a result",',
      '      "fix": "concrete change to make",',
      '      "effort": "S" | "M" | "L"',
      "    }",
      "  ],",
      '  "prioritized": ["F-01", "F-02", ...]',
      "}",
      "```",
      "",
      "**Prioritization rule** — sort by `severity` first (blocker > major > minor), then by `impact ÷ effort`.",
      "",
      "**Common mistakes**",
      '- Listing taste preferences as findings (`"I would use a different blue"`) — keep findings factual and tied to the audit checklist.',
      "- Treating every minor inconsistency as a blocker.",
      "- Producing a long list without prioritization.",
      "- Suggesting a fix without naming the underlying observation.",
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if you do not know the screen's intended primary action.",
      "- STOP if your findings list contains zero blockers AND the screen has missing states — re-audit step 3.",
      "- STOP if any finding has `\"fix\": null` — every finding must have an actionable fix.",
    ].join("\n"),
  },
  "accessibility-check": {
    id: "wf-accessibility",
    category: "workflow",
    title: "Accessibility Check",
    description: "Apply WCAG AA expectations.",
    content: [
      "### Accessibility Check",
      "1. Verify color contrast at AA for body and primary actions.",
      "2. Confirm keyboard reachability and focus order.",
      "3. Confirm semantic labels for screen readers.",
    ].join("\n"),
  },
  "implementation-prompt": {
    id: "wf-implementation-prompt",
    category: "workflow",
    title: "Implementation Prompt",
    description: "Produce an implementation-ready prompt for code agents.",
    content: [
      "### Implementation Prompt",
      "1. Summarize the screen, tokens, and components.",
      "2. State the target framework and styling system.",
      "3. Embed acceptance criteria and edge cases.",
    ].join("\n"),
  },
};

export function workflowBlocksFor(modules: WorkflowModule[]): SkillBlock[] {
  return modules.map((m) => WORKFLOW_BLOCKS[m]).filter(Boolean);
}
