import type { SkillBlock, SkillCategory, WorkflowModule } from "@/types/skill";

export const WORKFLOW_BLOCKS: Record<WorkflowModule, SkillBlock> = {
  "problem-definition": {
    id: "wf-problem-definition",
    category: "workflow",
    title: "Problem Definition",
    description: "Restate the user problem in concrete terms before producing screens.",
    content: [
      "### Problem Definition",
      "",
      "**When to enter this mode**",
      "- User describes a feature, screen, or product as a paragraph or shorter.",
      '- User says "design X" without providing existing screens.',
      "- A prior `ux-review` flagged a structural problem requiring a rethink.",
      "",
      "**Required inputs**",
      "- One sentence describing what the user wants.",
      "- The primary user role.",
      '- The success state — what does "done" look like, observably?',
      "",
      "If any input is missing, **ASK** before producing anything.",
      "",
      "**Steps**",
      "",
      "1. **Restate** the user's request in this exact form:",
      "   `[User role] wants to [action] so that [outcome].`",
      "   If you cannot fit it in one sentence, the problem is not one problem — split it.",
      "",
      "2. **Identify the primary user precisely.**",
      '   `"Customer"` is too vague. `"First-time customer who lands from a marketing email"` is precise.',
      "   Note what they already know and what they don't.",
      "",
      "3. **Map the trigger.** Where did the user come from? What just happened?",
      '   A user from `"Forgot password"` has a different mental state than one logging in fresh.',
      "",
      "4. **List unknowns.** Every assumption you'd have to make.",
      "   For each: (a) ask the user, (b) reasonable default, or (c) defer.",
      "",
      "5. **Define success** as observable behavior, not feelings.",
      '   `"User completes signup"` — observable. `"User feels confident"` — not.',
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "problem": "[Role] wants to [action] so that [outcome].",',
      '  "user": { "role": "...", "context": "...", "knownState": "..." },',
      '  "trigger": "...",',
      '  "successCriteria": ["observable behavior 1", "observable behavior 2"],',
      '  "unknowns": [',
      '    { "question": "...", "resolution": "ask" | "default" | "defer", "default": "..." }',
      "  ]",
      "}",
      "```",
      "",
      "**Common mistakes**",
      "- Restating the user's words verbatim instead of synthesizing.",
      '- Calling the user `"the customer"` without specifying *which* customer.',
      "- Skipping the trigger — leads to designing a screen out of context.",
      '- Defining success as `"fewer support tickets"` — true but not actionable here.',
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if you cannot fill the problem sentence in the required form.",
      "- STOP if `successCriteria` contains a feeling rather than a behavior.",
      "- STOP if `unknowns` is empty AND the user's request is shorter than 3 sentences — you missed assumptions.",
    ].join("\n"),
  },
  "user-flow": {
    id: "wf-user-flow",
    category: "workflow",
    title: "User Flow",
    description: "Map the happy-path and key alternates.",
    content: [
      "### User Flow",
      "1. List the happy-path steps from entry to success.",
      "2. Mark every decision point with explicit branches.",
      "3. Annotate failure or empty states.",
    ].join("\n"),
  },
  "information-architecture": {
    id: "wf-ia",
    category: "workflow",
    title: "Information Architecture",
    description: "Define screens, navigation, and content hierarchy.",
    content: [
      "### Information Architecture",
      "1. Enumerate the screens involved.",
      "2. Define the navigation model (tabs, stack, modal).",
      "3. Rank content priority within each screen.",
    ].join("\n"),
  },
  "screen-design": {
    id: "wf-screen-design",
    category: "workflow",
    title: "Screen Design",
    description: "Produce screen-level specs with hierarchy and primary action.",
    content: [
      "### Screen Design",
      "",
      "**When to enter this mode**",
      "- `problem-definition` and at least one of `user-flow` / `information-architecture` are complete.",
      "- User asks for a specific screen by name.",
      "",
      "**Required inputs**",
      "- Screen name and purpose (one sentence).",
      "- Entry point and exit point in the flow.",
      "- Primary user role for this screen.",
      "",
      "If any input is missing, **ASK** before proceeding.",
      "",
      "**Decision rules**",
      "- If the primary action is unclear, list candidate actions and let the user pick. Do not guess.",
      '- If two actions compete for "primary," one is wrong. Demote or split the screen.',
      "- If you cannot name the empty state's `next step`, the empty state is broken — fix it before continuing.",
      "- If you cannot describe an error state in one sentence, you don't understand the failure mode.",
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "screen": "ScreenName",',
      '  "purpose": "one sentence",',
      '  "primaryAction": { "label": "...", "destination": "..." },',
      '  "hierarchy": ["most important", "second", "third"],',
      '  "components": [',
      '    { "name": "ComponentName", "purpose": "...", "variants": ["..."], "states": ["..."] }',
      "  ],",
      '  "states": {',
      '    "default": "...",',
      '    "empty": { "trigger": "no data", "design": "...", "nextStep": "..." },',
      '    "loading": "skeleton shape",',
      '    "error": { "trigger": "...", "design": "...", "recovery": "..." }',
      "  },",
      '  "responsive": {',
      '    "mobile": "single column, sticky bottom CTA",',
      '    "tablet": "...",',
      '    "desktop": "..."',
      "  }",
      "}",
      "```",
      "",
      "**Common mistakes**",
      "- Listing UI elements before naming the primary action.",
      '- Treating `"empty"` as a missing screen instead of a designed state.',
      "- Componentizing too early — name the screen-level structure first.",
      '- Designing only the happy path. The error state is part of the design, not an afterthought.',
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if `primaryAction` is missing.",
      "- STOP if any of `{default, empty, loading, error}` is unspecified.",
      "- STOP if `hierarchy` has more than 5 items — the screen is overloaded.",
      "- STOP if any responsive variant is `\"same as desktop\"` — that's not a design decision.",
    ].join("\n"),
  },
  "component-breakdown": {
    id: "wf-component-breakdown",
    category: "workflow",
    title: "Component Breakdown",
    description: "Decompose screens into reusable components.",
    content: [
      "### Component Breakdown",
      "1. Identify reusable components across screens.",
      "2. Define props, variants, and states per component.",
      "3. Note responsive behavior and breakpoints.",
    ].join("\n"),
  },
  "design-system-draft": {
    id: "wf-design-system-draft",
    category: "workflow",
    title: "Design System Draft",
    description: "Draft the token and primitive layer.",
    content: [
      "### Design System Draft",
      "1. Propose color, typography, spacing, and radius tokens.",
      "2. Define primitive components (Button, Input, Card, etc.).",
      "3. Map screen elements to tokens and primitives.",
    ].join("\n"),
  },
  "figma-to-code": {
    id: "wf-figma-to-code",
    category: "workflow",
    title: "Figma to Code",
    description: "Translate visual specs into implementation plans.",
    content: [
      "### Figma to Code",
      "1. Produce a scene graph of the screen.",
      "2. Map each node to a component and its tokens.",
      "3. Output a Tailwind/React implementation outline.",
    ].join("\n"),
    dependencies: ["component-breakdown"],
  },
  "ux-review": {
    id: "wf-ux-review",
    category: "workflow",
    title: "UX Review",
    description: "Review existing screens against rules and surface prioritized issues.",
    content: [
      "### UX Review",
      "",
      "**When to enter this mode**",
      "- User provides an existing screen (screenshot, Figma link, URL, code) and asks for review.",
      '- User says variations like `"review this"`, `"find issues"`, `"what would you improve"`.',
      "",
      "**Required inputs**",
      "- The screen artifact (image / code / URL).",
      "- The screen's intended primary action (ASK if not provided — the review depends on it).",
      "- The primary user role.",
      "",
      "**Audit checklist (run in order)**",
      "",
      "1. **Primary action audit**",
      "   - Can a first-time user identify the primary action in under 3 seconds?",
      "   - Is the primary action visually dominant (size, contrast, isolation)?",
      "   - If no — that is the top finding. Stop the rest of the audit until this is resolved.",
      "",
      "2. **Hierarchy audit**",
      "   - Rank content priority by reading order. Does the design match the rank?",
      "   - Find any element that is visually heavy but informationally minor (and vice versa).",
      "",
      "3. **States audit**",
      "   - Default present. Empty present? Loading present? Error present?",
      "   - For each missing state, flag as a finding.",
      "",
      "4. **Accessibility audit**",
      "   - Color contrast at AA (4.5:1 body, 3:1 large text).",
      "   - Keyboard reachability and visible focus.",
      "   - Touch targets ≥ 44 px (mobile) / 32 px (desktop).",
      "",
      "5. **Consistency audit**",
      "   - Same intent expressed two different ways? (e.g., two button styles for the same action.)",
      "   - Spacing snaps to the grid?",
      "",
      "6. **Microcopy audit**",
      '   - Button labels are verbs and concrete (`"Save changes"` not `"OK"`).',
      "   - Error messages explain what failed AND what to do next.",
      "",
      "**Required output shape**",
      "",
      "```json",
      "{",
      '  "summary": "one-line verdict",',
      '  "findings": [',
      "    {",
      '      "id": "F-01",',
      '      "category": "primary-action" | "hierarchy" | "states" | "accessibility" | "consistency" | "microcopy",',
      '      "severity": "blocker" | "major" | "minor",',
      '      "observation": "what is wrong (factual)",',
      '      "impact": "what the user experiences as a result",',
      '      "fix": "concrete change to make",',
      '      "effort": "S" | "M" | "L"',
      "    }",
      "  ],",
      '  "prioritized": ["F-01", "F-02", ...]',
      "}",
      "```",
      "",
      "**Prioritization rule** — sort by `severity` first (blocker > major > minor), then by `impact ÷ effort`.",
      "",
      "**Common mistakes**",
      '- Listing taste preferences as findings (`"I would use a different blue"`) — keep findings factual and tied to the audit checklist.',
      "- Treating every minor inconsistency as a blocker.",
      "- Producing a long list without prioritization.",
      "- Suggesting a fix without naming the underlying observation.",
      "",
      "**Quality gates (STOP rules)**",
      "- STOP if you do not know the screen's intended primary action.",
      "- STOP if your findings list contains zero blockers AND the screen has missing states — re-audit step 3.",
      "- STOP if any finding has `\"fix\": null` — every finding must have an actionable fix.",
    ].join("\n"),
  },
  "accessibility-check": {
    id: "wf-accessibility",
    category: "workflow",
    title: "Accessibility Check",
    description: "Apply WCAG AA expectations.",
    content: [
      "### Accessibility Check",
      "1. Verify color contrast at AA for body and primary actions.",
      "2. Confirm keyboard reachability and focus order.",
      "3. Confirm semantic labels for screen readers.",
    ].join("\n"),
  },
  "implementation-prompt": {
    id: "wf-implementation-prompt",
    category: "workflow",
    title: "Implementation Prompt",
    description: "Produce an implementation-ready prompt for code agents.",
    content: [
      "### Implementation Prompt",
      "1. Summarize the screen, tokens, and components.",
      "2. State the target framework and styling system.",
      "3. Embed acceptance criteria and edge cases.",
    ].join("\n"),
  },

  // ── Frontend Implementation ────────────────────────────────────────────────
  "code-architecture": {
    id: "wf-code-architecture",
    category: "workflow",
    title: "Code Architecture",
    description: "Decide the file/folder layout, boundaries, and data flow.",
    content: [
      "### Code Architecture",
      "1. Map components, hooks, and utils to folders by feature, not by type.",
      "2. Identify the data-flow direction (props down, events up; or store).",
      "3. Define module boundaries — no cross-feature imports without an interface.",
    ].join("\n"),
  },
  "component-implementation": {
    id: "wf-component-implementation",
    category: "workflow",
    title: "Component Implementation",
    description: "Implement a single component from spec with full state coverage.",
    content: [
      "### Component Implementation",
      "1. Translate the spec's props into a typed component signature.",
      "2. Implement default, empty, loading, and error states explicitly.",
      "3. Wire keyboard interaction and focus management before styling.",
      "4. Add a Storybook entry or test file with all variants and states.",
    ].join("\n"),
  },
  "state-management": {
    id: "wf-state-management",
    category: "workflow",
    title: "State Management",
    description: "Pick local vs shared vs server state, and the right tool.",
    content: [
      "### State Management",
      "1. Classify each piece of state: local / shared / server / URL.",
      "2. Default to local. Promote to shared only when ≥3 components need it.",
      "3. Server state belongs in a query library (React Query / SWR), not Redux.",
    ].join("\n"),
  },
  "routing-strategy": {
    id: "wf-routing-strategy",
    category: "workflow",
    title: "Routing Strategy",
    description: "Define URL structure, params, and code-splitting boundaries.",
    content: [
      "### Routing Strategy",
      "1. URLs reflect content hierarchy and are sharable.",
      "2. Query params for filters and sort; path params for entities.",
      "3. Code-split per route; preload on hover for above-the-fold links.",
    ].join("\n"),
  },
  "performance-budget": {
    id: "wf-performance-budget",
    category: "workflow",
    title: "Performance Budget",
    description: "Set and enforce performance targets at the component level.",
    content: [
      "### Performance Budget",
      "1. Targets: LCP < 2.5s, CLS = 0 above the fold, JS < 250KB initial.",
      "2. Lazy-load below-the-fold images and routes.",
      "3. Memoize expensive renders only after profiling, not preemptively.",
    ].join("\n"),
  },
  "accessibility-implementation": {
    id: "wf-accessibility-implementation",
    category: "workflow",
    title: "Accessibility Implementation",
    description: "Translate accessibility checks into code-level patterns.",
    content: [
      "### Accessibility Implementation",
      "1. Every interactive element is reachable by Tab in logical order.",
      "2. Use semantic HTML first; ARIA only when semantics fall short.",
      "3. Visible focus ring at all times; never `outline: 0` without a replacement.",
      "4. Honor `prefers-reduced-motion` for any non-essential animation.",
    ].join("\n"),
  },

  // ── Design System Generator ────────────────────────────────────────────────
  "token-system": {
    id: "wf-token-system",
    category: "workflow",
    title: "Token System",
    description: "Design semantic tokens and their reference chain.",
    content: [
      "### Token System",
      "1. Define raw tokens (color values, type scale, spacing units).",
      "2. Reference them as semantic tokens (surface, ink, accent, hairline).",
      "3. Components consume *semantic* tokens only. Raw values never enter component code.",
      "4. Emit tokens as JSON; map to Tailwind theme keys and CSS variables.",
    ].join("\n"),
  },
  "primitive-design": {
    id: "wf-primitive-design",
    category: "workflow",
    title: "Primitive Design",
    description: "Specify the base components everything else composes from.",
    content: [
      "### Primitive Design",
      "1. Identify the irreducible primitives (Button, Input, Card, Modal, Toast, etc.).",
      "2. For each: define props, variants, states, and accessibility behavior.",
      "3. Primitives have no business logic — only presentation and interaction.",
    ].join("\n"),
  },
  "variant-system": {
    id: "wf-variant-system",
    category: "workflow",
    title: "Variant System",
    description: "Define the variant + state matrix per primitive.",
    content: [
      "### Variant System",
      "1. Variants are intent-driven (primary / secondary / destructive), not visual.",
      "2. States are always 4-tuple: default / hover / active / disabled.",
      "3. Cap variants per primitive at 5 — more means a missing primitive.",
    ].join("\n"),
    dependencies: ["primitive-design"],
  },
  "documentation-strategy": {
    id: "wf-documentation-strategy",
    category: "workflow",
    title: "Documentation Strategy",
    description: "Decide how the system is taught to its users.",
    content: [
      "### Documentation Strategy",
      "1. Each primitive has: purpose, props table, do/don't examples, accessibility notes.",
      "2. Tokens are documented with both the raw value and the semantic name.",
      "3. Show *one* canonical usage per component; avoid kitchen-sink demos.",
    ].join("\n"),
  },
  "migration-plan": {
    id: "wf-migration-plan",
    category: "workflow",
    title: "Migration Plan",
    description: "Plan adoption from an existing UI to the new system.",
    content: [
      "### Migration Plan",
      "1. Audit existing UI — map current patterns to new primitives.",
      "2. Prioritize migration by traffic and visual prominence.",
      "3. Allow legacy + new to coexist during transition; never block product work.",
    ].join("\n"),
    dependencies: ["token-system", "primitive-design"],
  },

  // ── Harness Setup ──────────────────────────────────────────────────────────
  "harness-target-selection": {
    id: "wf-harness-target-selection",
    category: "workflow",
    title: "Harness Target Selection",
    description: "Pick which agent harness this skill is being installed into.",
    content: [
      "### Harness Target Selection",
      "1. Identify the harness: Claude Code, Cursor, Codex, Windsurf, generic.",
      "2. Note the harness's expected skill install path (e.g., `~/.claude/skills/`).",
      "3. Note any harness-specific file formats (`.mdc` for Cursor, `AGENTS.md` for Codex).",
    ].join("\n"),
  },
  "harness-permissions": {
    id: "wf-harness-permissions",
    category: "workflow",
    title: "Harness Permissions",
    description: "Declare what tools/files the skill needs access to.",
    content: [
      "### Harness Permissions",
      "1. List required read paths, write paths, and shell commands.",
      "2. Prefer least-privilege defaults; expand only as the skill needs.",
      "3. Emit the matching `settings.json` permission block for the target harness.",
    ].join("\n"),
  },
  "harness-hooks": {
    id: "wf-harness-hooks",
    category: "workflow",
    title: "Harness Hooks",
    description: "Wire pre/post hooks for tool calls or session events.",
    content: [
      "### Harness Hooks",
      "1. Identify events that need automatic behavior (PreToolUse, PostToolUse, etc.).",
      "2. For each, specify the matcher and the action (script path or inline command).",
      "3. Hooks must be idempotent and fast — never block on network calls.",
    ].join("\n"),
  },
  "harness-install-flow": {
    id: "wf-harness-install-flow",
    category: "workflow",
    title: "Harness Install Flow",
    description: "Produce a copy-pasteable install procedure.",
    content: [
      "### Harness Install Flow",
      "1. State the exact directory the package goes into for the target harness.",
      "2. Emit a one-line shell command (or two) that installs the package.",
      "3. State how the user verifies installation (e.g., `claude /skills list`).",
    ].join("\n"),
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Which workflow modules apply to which category
// ─────────────────────────────────────────────────────────────────────────────

const UX_UI_WORKFLOWS: WorkflowModule[] = [
  "problem-definition",
  "user-flow",
  "information-architecture",
  "screen-design",
  "component-breakdown",
  "design-system-draft",
  "figma-to-code",
  "ux-review",
  "accessibility-check",
  "implementation-prompt",
];

const FRONTEND_WORKFLOWS: WorkflowModule[] = [
  "code-architecture",
  "component-implementation",
  "state-management",
  "routing-strategy",
  "performance-budget",
  "accessibility-implementation",
];

const DESIGN_SYSTEM_WORKFLOWS: WorkflowModule[] = [
  "token-system",
  "primitive-design",
  "variant-system",
  "documentation-strategy",
  "migration-plan",
];

const HARNESS_WORKFLOWS: WorkflowModule[] = [
  "harness-target-selection",
  "harness-permissions",
  "harness-hooks",
  "harness-install-flow",
];

export const WORKFLOW_BY_CATEGORY: Record<SkillCategory, WorkflowModule[]> = {
  "ux-ui": UX_UI_WORKFLOWS,
  frontend: FRONTEND_WORKFLOWS,
  "design-system": DESIGN_SYSTEM_WORKFLOWS,
  harness: HARNESS_WORKFLOWS,
  product: [],
  research: [],
  content: [],
  data: [],
};

export function workflowBlocksFor(modules: WorkflowModule[]): SkillBlock[] {
  return modules.map((m) => WORKFLOW_BLOCKS[m]).filter(Boolean);
}
