import type { SkillPackageType } from "@/types/skill";

/**
 * Lightweight descriptive metadata layered on top of the SkillConfig
 * generated by each preset. Used by the UI to render preset impact
 * summaries, focus labels, and "added / removed" highlights — does
 * not feed back into generation.
 */
export type PresetBundle = {
  id: string;
  focus: { en: string; ko: string };
  includedSkillTypes: SkillPackageType[];
  primaryKitStructure: SkillPackageType;
  /** File groups the preset emphasizes (Generated Files section labels). */
  expectedFileGroups: string[];
  /** Specific files the preset puts forward as the headline artifact. */
  emphasizedFiles: string[];
};

export const PRESET_BUNDLES: Record<string, PresetBundle> = {
  "ux-ui-axdd-default": {
    id: "ux-ui-axdd-default",
    focus: { en: "Full UX/UI workflow", ko: "전체 UX/UI 워크플로" },
    includedSkillTypes: [
      "full-step-skill",
      "reference-skill",
      "template-skill",
      "test-skill",
    ],
    primaryKitStructure: "full-step-skill",
    expectedFileGroups: [
      "Core",
      "Workflow",
      "Knowledge",
      "Templates",
      "Checklists",
      "Tests",
      "Examples",
    ],
    emphasizedFiles: [
      "WORK_UNIT.json",
      "HOOKS.json",
      "references/stage-guides/",
      "references/skill-framework.md",
    ],
  },
  "axdd-ux-ui-reference-review": {
    id: "axdd-ux-ui-reference-review",
    focus: { en: "Review & validation", ko: "리뷰 및 검증" },
    includedSkillTypes: ["reference-skill", "test-skill"],
    primaryKitStructure: "test-skill",
    expectedFileGroups: [
      "Core",
      "Knowledge",
      "Checklists",
      "Tests",
      "Examples",
    ],
    emphasizedFiles: [
      "templates/design-review-template.md",
      "checklists/ui-design-checklist.md",
      "tests/sandbox-test-scenario.md",
    ],
  },
  "axdd-cursor-handoff-kit": {
    id: "axdd-cursor-handoff-kit",
    focus: { en: "Implementation handoff", ko: "구현 핸드오프" },
    includedSkillTypes: ["template-skill", "reference-skill", "test-skill"],
    primaryKitStructure: "template-skill",
    expectedFileGroups: [
      "Core",
      "Knowledge",
      "Templates",
      "Checklists",
      "Tests",
      "Examples",
    ],
    emphasizedFiles: [
      "templates/cursor-prompt-template.md",
      "checklists/handoff-checklist.md",
      "checklists/release-checklist.md",
    ],
  },
  "axdd-figma-manual-instruction-kit": {
    id: "axdd-figma-manual-instruction-kit",
    focus: { en: "Manual Figma instructions", ko: "Figma 수동 지시" },
    includedSkillTypes: ["template-skill", "reference-skill"],
    primaryKitStructure: "template-skill",
    expectedFileGroups: ["Core", "Knowledge", "Templates", "Examples"],
    emphasizedFiles: [
      "templates/figma-instruction-template.md",
      "references/design-system-rules.md",
      "references/accessibility-checklist.md",
    ],
  },
  "axdd-ux-validation-governance-kit": {
    id: "axdd-ux-validation-governance-kit",
    focus: { en: "Validation & governance", ko: "검증 및 거버넌스" },
    includedSkillTypes: ["test-skill", "metadata-skill"],
    primaryKitStructure: "test-skill",
    expectedFileGroups: ["Core", "Checklists", "Tests", "Scripts & Metadata"],
    emphasizedFiles: [
      "tests/sandbox-test-scenario.md",
      "tests/validation-log-template.md",
      "KIT_MANIFEST.json",
      "metadata/index.json",
    ],
  },
};

export function getPresetBundle(presetId: string): PresetBundle | undefined {
  return PRESET_BUNDLES[presetId];
}

export type PresetDiff = {
  fromId: string;
  toId: string;
  addedTypes: SkillPackageType[];
  removedTypes: SkillPackageType[];
  primaryChanged: boolean;
  addedGroups: string[];
  removedGroups: string[];
};

export function diffPresets(fromId: string, toId: string): PresetDiff | null {
  const a = PRESET_BUNDLES[fromId];
  const b = PRESET_BUNDLES[toId];
  if (!a || !b) return null;
  const aSet = new Set(a.includedSkillTypes);
  const bSet = new Set(b.includedSkillTypes);
  const addedTypes = b.includedSkillTypes.filter((t) => !aSet.has(t));
  const removedTypes = a.includedSkillTypes.filter((t) => !bSet.has(t));
  const aGroups = new Set(a.expectedFileGroups);
  const bGroups = new Set(b.expectedFileGroups);
  const addedGroups = b.expectedFileGroups.filter((g) => !aGroups.has(g));
  const removedGroups = a.expectedFileGroups.filter((g) => !bGroups.has(g));
  return {
    fromId,
    toId,
    addedTypes,
    removedTypes,
    primaryChanged: a.primaryKitStructure !== b.primaryKitStructure,
    addedGroups,
    removedGroups,
  };
}
